name: Deploy Strapi to ECS

on:
  push:
    branches:
      - main  # or varun

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: strapi-varun-ecr-repo
  ECS_CLUSTER: strapi-varun-cluster
  ECS_SERVICE: strapi-varun-service
  ECS_TASK_DEFINITION: postgres17
  CONTAINER_NAME: strapi-varun-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$latest ./Strapi-app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$latest
        echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$latest" >> $GITHUB_ENV